 import { Wind, Car, Wifi, ShieldCheck } from 'lucide-react'; // Assuming Lucide icons based on your snippet
 export const PROPERTIES = [
  {
    id: 1,
    name: 'Skyline Penthouse — Tower One',
    tag: 'New',
    isRent: false,
    price: '3,850,000',
    period: '',
    loc: 'Midtown, Manhattan NY',
    beds: 4,
    baths: 3,
    sqft: 420,
    floors: 1,
    year: 2022,
    garage: 3,
    description: `A pinnacle of urban luxury, this penthouse offers 360-degree views of the Manhattan skyline. Featuring double-height ceilings and a private elevator gallery, it represents the ultimate in high-rise living.`,
    features: ['Private Elevator', 'Smart Home System', 'Floor-to-Ceiling Windows', 'Concierge Service'],
    amenities: [
      { icon: Wind, label: 'Central A/C' },
      { icon: ShieldCheck, label: '24/7 Security' },
      { icon: Wifi, label: 'Fiber Internet' },
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=85',
    ],
    agent: {
      name: 'Sophia Laurent',
      title: 'Senior Property Advisor',
      phone: '+1 (310) 555-0190',
      email: 'sophia@altisrealty.com',
      img: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80',
    },
  },
  {
    id: 2,
    name: 'Elysian Heights Villa',
    tag: 'For Sale',
    isRent: false,
    price: '2,450,000',
    period: '',
    loc: 'Beverly Hills, CA 90210',
    beds: 5,
    baths: 4,
    sqft: 620,
    floors: 3,
    year: 2019,
    garage: 2,
    description: `Nestled in the prestigious hills of Beverly Hills, Elysian Heights is a masterpiece of contemporary architecture blended with timeless elegance. Expansive floor-to-ceiling windows frame breathtaking panoramic views of the city.`,
    features: [
      'Heated infinity pool',
      'Smart home automation',
      'Private cinema room',
      'Wine cellar',
      'Electric vehicle charging',
    ],
    amenities: [
      { icon: Wind, label: 'Central A/C' },
      { icon: Car, label: '2-Car Garage' },
      { icon: Wifi, label: 'Fiber Internet' },
      { icon: ShieldCheck, label: '24/7 Security' },
    ],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=85',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=85',
    ],
    agent: {
      name: 'Sophia Laurent',
      title: 'Senior Property Advisor',
      phone: '+1 (310) 555-0190',
      email: 'sophia@altisrealty.com',
      img: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80',
    },
  },
  {
    id: 3,
    name: 'Meridian Sky Apartments',
    tag: 'For Rent',
    isRent: true,
    price: '8,500',
    period: '/mo',
    loc: 'Manhattan, New York',
    beds: 3,
    baths: 2,
    sqft: 185,
    floors: 1,
    year: 2021,
    garage: 1,
    description: `A sophisticated rental opportunity in the heart of Manhattan. This modern apartment features high-end finishes and access to world-class building amenities.`,
    features: ['Modern Kitchen', 'City Views', 'Hardwood Floors', 'Pet Friendly'],
    amenities: [
      { icon: Wind, label: 'Central A/C' },
      { icon: Wifi, label: 'High-Speed Wifi' },
    ],
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=85',
      'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1200&q=85',
    ],
    agent: {
      name: 'Sophia Laurent',
      title: 'Senior Property Advisor',
      phone: '+1 (310) 555-0190',
      email: 'sophia@altisrealty.com',
      img: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80',
    },
  },
];

export default PROPERTIES;
